---
- name: Including specific vars for Windows
  ansible.builtin.include_vars: "{{ ansible_system }}_{{ ansible_architecture }}_{{ role_name }}.yml"

# Set zip filename for releases with old naming convention
- name: Set filename of zip if target host is Windows (old naming convention)
  ansible.builtin.set_fact:
    zipFile: mqadv_dev{{ version }}_windows.zip
  when: ansible_os_family == 'Windows' and not local_source and convention=='old'

# Set zip filename for releases with new naming convention (>9.3)
- name: Set filename of zip if target host is Windows (new naming convention)
  ansible.builtin.set_fact:
    zipFile: '{{ vrmf }}-IBM-MQ-Advanced-for-Developers-Win64.zip'
  when: ansible_os_family == 'Windows' and not local_source and convention=='new'

- name: Download MQ Advanced for Developers on Windows
  ansible.windows.win_get_url:
    url: "{{ downloadURL }}{{ zipFile }}"
    dest: "{{ directory }}\\mq.zip"
    force: false
  tags: download
  when: ansible_os_family == 'Windows' and not local_source

- name: Copy local MQ source to target
  ansible.windows.win_copy:
    src: "{{ mq_local_path }}"
    dest: "{{ directory }}\\mq.zip"
  when: local_source

- name: Unzip MQ on Windows
  community.windows.win_unzip:
    src: "{{ directory }}\\mq.zip"
    remote_src: true
    dest: "{{ directory }}\\mq-install"
  tags: download
  when: ansible_os_family == 'Windows'
