---

- name: Check if license status file exists
  stat:
    path: /opt/MQServer/licensestatus.txt
  register: license_status

- name: Accept MQ license
  shell: |
    /opt/MQServer/mqlicense.sh -{{ ibmMqLicence}} > /opt/MQServer/licensestatus.txt
  changed_when: not license_status.stat.exists

- name: Find required rpm files
  find:
    paths: "/opt/MQServer"
    patterns:
      - MQSeriesSDK*
      - MQSeriesSamples*
      - MQSeriesMan*
      - MQSeriesClient*
      - MQSeriesGSKit*
      - MQSeriesAMQP*
      - MQSeriesAMS*
      - MQSeriesServer*
      - MQSeriesJRE*
      - MQSeriesJava*
      - MQSeriesRuntime*
      - MQSeriesWeb*
      - MQSeriesMsg_Zh_CN*
      - MQSeriesMsg_es*
    # - MQSeriesSFBridge-9.3.0-0.x86_64.rpm
    # - MQSeriesMsg_Zh_TW-9.3.0-0.x86_64.rpm
    # - MQSeriesFTTools-9.3.0-0.x86_64.rpm
    # - MQSeriesFTAgent-9.3.0-0.x86_64.rpm
    # - MQSeriesFTService-9.3.0-0.x86_64.rpm
    # - MQSeriesBCBridge-9.3.0-0.x86_64.rpm
    # - MQSeriesFTLogger-9.3.0-0.x86_64.rpm
    # - MQSeriesXRService-9.3.0-0.x86_64.rpm
    # - MQSeriesFTBase-9.3.0-0.x86_64.rpm
    # - MQSeriesMsg_fr-9.3.0-0.x86_64.rpm
    # - MQSeriesMsg_ja-9.3.0-0.x86_64.rpm
    # - MQSeriesMsg_it-9.3.0-0.x86_64.rpm
    # - MQSeriesMsg_ko-9.3.0-0.x86_64.rpm
    # - MQSeriesMsg_ru-9.3.0-0.x86_64.rpm
    # - MQSeriesMsg_pt-9.3.0-0.x86_64.rpm
    # - MQSeriesMsg_hu-9.3.0-0.x86_64.rpm
    # - MQSeriesMsg_pl-9.3.0-0.x86_64.rpm
    # - MQSeriesMsg_cs-9.3.0-0.x86_64.rpm
    # - MQSeriesMsg_fr-9.3.0-0.x86_64.rpm
    # - MQSeriesMsg_ja-9.3.0-0.x86_64.rpm
    # - MQSeriesMsg_it-9.3.0-0.x86_64.rpm
    # - MQSeriesMsg_ko-9.3.0-0.x86_64.rpm
    # - MQSeriesMsg_ru-9.3.0-0.x86_64.rpm
    # - MQSeriesMsg_pt-9.3.0-0.x86_64.rpm
    # - MQSeriesMsg_hu-9.3.0-0.x86_64.rpm
    # - MQSeriesMsg_pl-9.3.0-0.x86_64.rpm
    # - MQSeriesMsg_cs-9.3.0-0.x86_64.rpm
  register: rpm_files

- name: Create a list of paths to rpms from the found files
  set_fact:
    rpm_list: "{{ rpm_files.files | map(attribute='path') | list }}"

- name: Install IBM MQ
  ansible.builtin.dnf:
    name: "{{ rpm_list }}"
    state: present
    disable_gpg_check: true

- name: reset ssh connection
  meta: reset_connection